### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by RobLoach** [raysan5/rres#5]
Add CMake definition files.

**Comment by raysan5** [comment]
@RobLoach I'm afraid I'm not adding CMake for the moment. Main reason it's because I don't use CMake and I can not maintain/support it.

raylib CMake support was also added by a user, if issues arise they usually point to me and I can not take care of them.

I'll keep the PR on hold just in case for a future.

**Comment by RobLoach** [comment]
Thanks! :+1:
